/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RelatorioRouteImport } from './routes/relatorio'
import { Route as FluxosIndexRouteImport } from './routes/fluxos.index'
import { Route as FluxosSlugRouteImport } from './routes/fluxos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatorioRoute = RelatorioRouteImport.update({
  id: '/relatorio',
  path: '/relatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxosIndexRoute = FluxosIndexRouteImport.update({
  id: '/fluxos/',
  path: '/fluxos/',
  getParentRoute: () => rootRouteImport,
} as any)
const FluxosSlugRoute = FluxosSlugRouteImport.update({
  id: '/fluxos/$slug',
  path: '/fluxos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/relatorio': typeof RelatorioRoute
  '/fluxos/$slug': typeof FluxosSlugRoute
  '/fluxos/': typeof FluxosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/relatorio': typeof RelatorioRoute
  '/fluxos/$slug': typeof FluxosSlugRoute
  '/fluxos': typeof FluxosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/relatorio': typeof RelatorioRoute
  '/fluxos/$slug': typeof FluxosSlugRoute
  '/fluxos/': typeof FluxosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/relatorio' | '/fluxos/$slug' | '/fluxos/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/relatorio' | '/fluxos/$slug' | '/fluxos'
  id: '__root__' | '/' | '/relatorio' | '/fluxos/$slug' | '/fluxos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RelatorioRoute: typeof RelatorioRoute
  FluxosSlugRoute: typeof FluxosSlugRoute
  FluxosIndexRoute: typeof FluxosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorio': {
      id: '/relatorio'
      path: '/relatorio'
      fullPath: '/relatorio'
      preLoaderRoute: typeof RelatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxos/': {
      id: '/fluxos/'
      path: '/fluxos'
      fullPath: '/fluxos/'
      preLoaderRoute: typeof FluxosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fluxos/$slug': {
      id: '/fluxos/$slug'
      path: '/fluxos/$slug'
      fullPath: '/fluxos/$slug'
      preLoaderRoute: typeof FluxosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RelatorioRoute: RelatorioRoute,
  FluxosSlugRoute: FluxosSlugRoute,
  FluxosIndexRoute: FluxosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
